"""Token-level grammar for constrained decoding.

Instead of a character-level automaton, every state only allows
tokens that are valid in full ("all digits", "no quote"), so a
token can never straddle a grammar-state boundary. Structural
JSON (braces, keys, quotes, separators) is never generated by
the model; the decoder inserts it directly.

This package is split by concern:

- :mod:`src.grammar.tries` -- closed-choice literals (function
  names, booleans).
- :mod:`src.grammar.token_sets` -- precomputed allowed-token-id
  sets, derived once from the vocabulary.
- :mod:`src.grammar.fsm` -- per-value-type state machines (numbers,
  strings) built on top of those token sets.

Everything below is re-exported here so callers can keep writing
``from src.grammar import TokenSets`` without caring how the
package is internally organized.
"""

from src.grammar.fsm import NumberFSM, NumState, StringFSM
from src.grammar.token_sets import DIGITS, TokenSets
from src.grammar.tries import Trie, TrieNode, build_trie

__all__ = [
    "DIGITS",
    "NumState",
    "NumberFSM",
    "StringFSM",
    "TokenSets",
    "Trie",
    "TrieNode",
    "build_trie",
]
