"""Token-level finite state machines for JSON value bodies.

Each FSM only allows tokens that are valid in full at the current
state ("all digits", "no quote"), so a single generated token can
never straddle a grammar-state boundary. Structural JSON (braces,
keys, quotes, separators) is never generated by the model; the
decoder inserts it directly.
"""

from enum import Enum

from src.grammar.token_sets import TokenSets


class NumState(Enum):
    """States of :class:`NumberFSM`, in the order they're visited."""

    START = "START"
    INT_EMPTY = "INT_EMPTY"
    INT = "INT"
    FRAC_EMPTY = "FRAC_EMPTY"
    FRAC = "FRAC"
    DONE = "DONE"


class NumberFSM:
    """JSON number: -?digits(.digits)? ended by a terminator token.

    The terminator ("," or "}") is chosen by the model, since a
    number has no closing delimiter of its own.
    """

    def __init__(self, sets: TokenSets, term_id: int) -> None:
        """Set up the FSM to start reading a fresh number.

        Args:
            sets: The precomputed token-id sets for the vocabulary.
            term_id: The token id that ends the number (comma or
                closing brace, depending on parameter position).
        """
        self._sets = sets
        self._term = term_id
        self.state = NumState.START

    @property
    def done(self) -> bool:
        """True once the terminator token has been consumed."""
        return self.state is NumState.DONE

    def allowed(self) -> list[int]:
        """Token ids that are legal to generate in the current state."""
        sets = self._sets
        if self.state is NumState.START:
            return sets.digits + [sets.minus]
        if self.state in (NumState.INT_EMPTY, NumState.FRAC_EMPTY):
            return list(sets.digits)
        if self.state is NumState.INT:
            return sets.digits + [sets.dot, self._term]
        if self.state is NumState.FRAC:
            return sets.digits + [self._term]
        return []

    def advance(self, token_id: int) -> None:
        """Update the state after ``token_id`` has been generated."""
        if token_id == self._term:
            self.state = NumState.DONE
        elif self.state is NumState.START:
            if token_id == self._sets.minus:
                self.state = NumState.INT_EMPTY
            else:
                self.state = NumState.INT
        elif self.state is NumState.INT_EMPTY:
            self.state = NumState.INT
        elif self.state is NumState.INT:
            if token_id == self._sets.dot:
                self.state = NumState.FRAC_EMPTY
        elif self.state is NumState.FRAC_EMPTY:
            self.state = NumState.FRAC


class StringFSM:
    """JSON string body; the decoder inserts the opening quote.

    After max_tokens the only allowed token is the closing quote,
    so a string can never ramble forever.
    """

    def __init__(self, sets: TokenSets, max_tokens: int = 40) -> None:
        """Set up the FSM to start reading a fresh string body.

        Args:
            sets: The precomputed token-id sets for the vocabulary.
            max_tokens: Maximum number of body tokens before the
                closing quote becomes the only legal choice.
        """
        self._sets = sets
        self._max = max_tokens
        self._count = 0
        self.done = False

    def allowed(self) -> list[int]:
        """Token ids that are legal to generate in the current state."""
        if self._count >= self._max:
            return [self._sets.quote]
        return self._sets.string_body + [self._sets.quote]

    def advance(self, token_id: int) -> None:
        """Update the state after ``token_id`` has been generated."""
        if token_id == self._sets.quote:
            self.done = True
        else:
            self._count += 1
