"""Token-level grammar for constrained decoding.

Instead of a character-level automaton, every state only allows
tokens that are valid in full ("all digits", "no quote"), so a
token can never straddle a grammar-state boundary. Structural
JSON (braces, keys, quotes, separators) is never generated by
the model; the decoder inserts it directly.
"""

from dataclasses import dataclass, field
from enum import Enum

from src.tokenizer_vocab import token_to_bytes

DIGITS = set("0123456789")


@dataclass
class TrieNode:
    children: dict[int, "TrieNode"] = field(default_factory=dict)
    name: str | None = None


class Trie:
    """Trie over token-id sequences (function names, true/false)."""

    def __init__(self) -> None:
        self.root = TrieNode()

    def insert(self, ids: list[int], name: str) -> None:
        node = self.root
        for tid in ids:
            if tid not in node.children:
                node.children[tid] = TrieNode()
            node = node.children[tid]
        node.name = name


def build_trie(entries: list[tuple[list[int], str]]) -> Trie:
    trie = Trie()
    for ids, name in entries:
        trie.insert(ids, name)
    return trie


class TokenSets:
    """Precomputed allowed-token-id sets, built once from the vocab."""

    def __init__(self, vocab: dict[int, str]) -> None:
        by_str = {text: tid for tid, text in vocab.items()}
        self.quote = by_str['"']
        self.minus = by_str["-"]
        self.dot = by_str["."]
        self.comma = by_str[","]
        self.close_brace = by_str["}"]
        self.digits = [
            tid
            for tid, text in vocab.items()
            if all(ch in DIGITS for ch in text)
        ]
        self.string_body = [
            tid for tid, text in vocab.items() if _string_safe(text)
        ]


def _string_safe(text: str) -> bool:
    """True if the token can appear inside a JSON string body."""
    if text.startswith("<|"):
        return False
    raw = token_to_bytes(text)
    if b'"' in raw or b"\\" in raw:
        return False
    return all(byte >= 0x20 for byte in raw)


class NumState(Enum):
    START = "START"
    INT_EMPTY = "INT_EMPTY"
    INT = "INT"
    FRAC_EMPTY = "FRAC_EMPTY"
    FRAC = "FRAC"
    DONE = "DONE"


class NumberFSM:
    """JSON number: -?digits(.digits)? ended by a terminator token.

    The terminator ("," or "}") is chosen by the model, since a
    number has no closing delimiter of its own.
    """

    def __init__(self, sets: TokenSets, term_id: int) -> None:
        self._sets = sets
        self._term = term_id
        self.state = NumState.START

    @property
    def done(self) -> bool:
        return self.state is NumState.DONE

    def allowed(self) -> list[int]:
        sets = self._sets
        if self.state is NumState.START:
            return sets.digits + [sets.minus]
        if self.state in (NumState.INT_EMPTY, NumState.FRAC_EMPTY):
            return list(sets.digits)
        if self.state is NumState.INT:
            return sets.digits + [sets.dot, self._term]
        if self.state is NumState.FRAC:
            return sets.digits + [self._term]
        return []

    def advance(self, token_id: int) -> None:
        if token_id == self._term:
            self.state = NumState.DONE
        elif self.state is NumState.START:
            if token_id == self._sets.minus:
                self.state = NumState.INT_EMPTY
            else:
                self.state = NumState.INT
        elif self.state is NumState.INT_EMPTY:
            self.state = NumState.INT
        elif self.state is NumState.INT:
            if token_id == self._sets.dot:
                self.state = NumState.FRAC_EMPTY
        elif self.state is NumState.FRAC_EMPTY:
            self.state = NumState.FRAC


class StringFSM:
    """JSON string body; the decoder inserts the opening quote.

    After max_tokens the only allowed token is the closing quote,
    so a string can never ramble forever.
    """

    def __init__(self, sets: TokenSets, max_tokens: int = 40) -> None:
        self._sets = sets
        self._max = max_tokens
        self._count = 0
        self.done = False

    def allowed(self) -> list[int]:
        if self._count >= self._max:
            return [self._sets.quote]
        return self._sets.string_body + [self._sets.quote]

    def advance(self, token_id: int) -> None:
        if token_id == self._sets.quote:
            self.done = True
        else:
            self._count += 1
